<?php

use Illuminate\Database\Seeder;

class CompRegionConfigsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('comp_region_configs')->delete();

        \DB::table('comp_region_configs')->insert(array (
            0 =>
            array (
                'id' => 1,
                'company_id' => '201',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'company_id' => '1000',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'company_id' => '1000',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'company_id' => '1000',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'company_id' => '1001',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'company_id' => '1001',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'company_id' => '1001',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'company_id' => '1002',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'company_id' => '1002',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'company_id' => '1002',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'company_id' => '1003',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'company_id' => '1003',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'company_id' => '1003',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'company_id' => '1010',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'company_id' => '1010',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'company_id' => '1010',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'company_id' => '1020',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'company_id' => '1030',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'company_id' => '1040',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'company_id' => '1040',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'company_id' => '1040',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'company_id' => '1050',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'company_id' => '1060',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'company_id' => '1060',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'company_id' => '1060',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'company_id' => '1070',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'company_id' => '1070',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'company_id' => '1070',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'company_id' => '1071',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'company_id' => '1071',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'company_id' => '1071',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'company_id' => '1072',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'company_id' => '1072',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'company_id' => '1072',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'company_id' => '1080',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'company_id' => '1080',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'company_id' => '1080',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'company_id' => '1090',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'company_id' => '1090',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'company_id' => '1090',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'company_id' => '1141',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'company_id' => '1141',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'company_id' => '1141',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            43 =>
            array (
                'id' => 50,
                'company_id' => '3001',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'id' => 51,
                'company_id' => '3001',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            45 =>
            array (
                'id' => 52,
                'company_id' => '3001',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            46 =>
            array (
                'id' => 53,
                'company_id' => '3002',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 54,
                'company_id' => '3002',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            48 =>
            array (
                'id' => 55,
                'company_id' => '3002',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            49 =>
            array (
                'id' => 56,
                'company_id' => '3004',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            50 =>
            array (
                'id' => 57,
                'company_id' => '3005',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            51 =>
            array (
                'id' => 58,
                'company_id' => '3005',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            52 =>
            array (
                'id' => 59,
                'company_id' => '3006',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            53 =>
            array (
                'id' => 60,
                'company_id' => '3201',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            54 =>
            array (
                'id' => 61,
                'company_id' => 'ESOS',
                'region' => 'SEM',
                'salary_cap' => '2000.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            55 =>
            array (
                'id' => 62,
                'company_id' => 'ESOS',
                'region' => 'SBH',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
            56 =>
            array (
                'id' => 63,
                'company_id' => 'ESOS',
                'region' => 'SWK',
                'salary_cap' => '2500.00',
                'hourperday' => 7,
                'hourpermonth' => 104,
                'daypermonth' => 26,
                'start_date' => '1970-11-20',
                'end_date' => '9999-12-31',
                'created_by' => 53062,
                'deleted_at' => NULL,
                'created_at' => '1970-11-20 00:00:00',
                'updated_at' => NULL,
            ),
        ));


    }
}
