<?php

use Illuminate\Database\Seeder;

class DayTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('day_types')->delete();
        
        \DB::table('day_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => '2019-11-08 12:28:56',
                'updated_at' => '2019-11-11 12:15:06',
                'deleted_at' => '2019-11-11 12:15:06',
                'code' => 'NOR1',
                'description' => 'Normal WorkDay',
                'is_work_day' => 1,
                'start_time' => '08:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => 43570,
                'deleted_by' => 43570,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => '2019-11-11 12:18:31',
                'updated_at' => '2019-11-11 12:18:31',
                'deleted_at' => NULL,
                'code' => 'NOR1',
                'description' => 'Normal WorkDay',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => '2019-11-11 12:43:01',
                'updated_at' => '2019-11-11 12:43:01',
                'deleted_at' => NULL,
                'code' => 'NFRI',
            'description' => 'Normal (Friday)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 8,
                'dur_minute' => 30,
                'total_minute' => 510,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => '2019-11-11 12:52:02',
                'updated_at' => '2019-11-11 12:58:47',
                'deleted_at' => NULL,
                'code' => 'OFFD',
                'description' => 'Off Day',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 43570,
                'last_edited_by' => 43570,
                'deleted_by' => NULL,
                'bg_color' => '#e85edd',
                'font_color' => '#5731a6',
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => '2019-11-11 12:58:19',
                'updated_at' => '2019-11-11 12:58:19',
                'deleted_at' => NULL,
                'code' => 'RSTD',
                'description' => 'Rest Day',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#f36dc1',
                'font_color' => '#3235c0',
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => '2019-11-11 13:05:22',
                'updated_at' => '2019-11-11 13:05:22',
                'deleted_at' => NULL,
                'code' => 'NTHU',
            'description' => 'Normal (Thurs)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 8,
                'dur_minute' => 30,
                'total_minute' => 510,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => '2019-11-11 14:17:09',
                'updated_at' => '2019-11-11 14:17:09',
                'deleted_at' => NULL,
                'code' => 'NOR2',
                'description' => 'Normal WorkDay2',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 8,
                'dur_minute' => 30,
                'total_minute' => 510,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            7 => 
            array (
                'id' => 8,
                'created_at' => '2019-11-11 14:25:21',
                'updated_at' => '2019-11-11 14:33:35',
                'deleted_at' => '2019-11-11 14:33:35',
                'code' => 'HSAT',
            'description' => 'HalfDay (Sat)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 4,
                'dur_minute' => 25,
                'total_minute' => 265,
                'created_by' => 43570,
                'last_edited_by' => 43570,
                'deleted_by' => 43570,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            8 => 
            array (
                'id' => 9,
                'created_at' => '2019-11-11 14:28:34',
                'updated_at' => '2019-11-11 14:28:34',
                'deleted_at' => NULL,
                'code' => 'HTHU',
            'description' => 'HalfDay (Thur)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 4,
                'dur_minute' => 30,
                'total_minute' => 270,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            9 => 
            array (
                'id' => 10,
                'created_at' => '2019-11-11 14:41:31',
                'updated_at' => '2019-11-11 14:41:56',
                'deleted_at' => '2019-11-11 14:41:56',
                'code' => 'HSAT',
            'description' => 'HalfDay (Sat)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 4,
                'dur_minute' => 45,
                'total_minute' => 285,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => 43570,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            10 => 
            array (
                'id' => 11,
                'created_at' => '2019-11-11 14:43:00',
                'updated_at' => '2019-11-11 14:43:00',
                'deleted_at' => NULL,
                'code' => 'HSAT',
            'description' => 'HalfDay (Sat)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 4,
                'dur_minute' => 15,
                'total_minute' => 255,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            11 => 
            array (
                'id' => 12,
                'created_at' => '2019-11-11 14:50:09',
                'updated_at' => '2019-11-11 14:50:09',
                'deleted_at' => NULL,
                'code' => 'NOR3',
                'description' => 'Normal WorkDay3',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 8,
                'dur_minute' => 15,
                'total_minute' => 495,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            12 => 
            array (
                'id' => 13,
                'created_at' => '2019-11-11 15:14:20',
                'updated_at' => '2019-11-11 15:14:20',
                'deleted_at' => NULL,
                'code' => 'NOR6',
                'description' => 'Normal WD GT&RD',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            13 => 
            array (
                'id' => 14,
                'created_at' => '2019-11-11 15:16:37',
                'updated_at' => '2019-11-11 15:16:37',
                'deleted_at' => NULL,
                'code' => 'NOR7',
                'description' => 'Normal WD VADS',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            14 => 
            array (
                'id' => 15,
                'created_at' => '2019-11-11 15:18:51',
                'updated_at' => '2019-11-11 15:18:51',
                'deleted_at' => NULL,
                'code' => 'NOR8',
                'description' => 'Normal WD TAB',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            15 => 
            array (
                'id' => 16,
                'created_at' => '2019-11-11 15:19:54',
                'updated_at' => '2019-11-11 15:19:54',
                'deleted_at' => NULL,
                'code' => 'NOR9',
                'description' => 'Normal WD TMIM',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            16 => 
            array (
                'id' => 17,
                'created_at' => '2019-11-11 15:21:18',
                'updated_at' => '2019-11-11 15:21:18',
                'deleted_at' => NULL,
                'code' => 'NOWD',
                'description' => 'Normal WD webe',
                'is_work_day' => 1,
                'start_time' => '09:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            17 => 
            array (
                'id' => 18,
                'created_at' => '2019-11-11 16:27:58',
                'updated_at' => '2019-11-11 16:27:58',
                'deleted_at' => NULL,
                'code' => 'NFRT',
            'description' => 'NormalFR(TSSSB)',
                'is_work_day' => 1,
                'start_time' => '09:00:00',
                'dur_hour' => 8,
                'dur_minute' => 30,
                'total_minute' => 510,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
        ));
        
        
    }
}