<?php

use Illuminate\Database\Seeder;

class DayTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('day_types')->delete();
        
        \DB::table('day_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => '2019-11-08 12:28:56',
                'updated_at' => '2019-11-11 12:15:06',
                'deleted_at' => '2019-11-11 12:15:06',
                'code' => 'NOR1',
                'description' => 'Normal WorkDay',
                'is_work_day' => 1,
                'start_time' => '08:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => 43570,
                'deleted_by' => 43570,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => '2019-11-11 12:18:31',
                'updated_at' => '2019-11-11 12:18:31',
                'deleted_at' => NULL,
                'code' => 'NOR1',
                'description' => 'Normal WorkDay',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => '2019-11-11 12:43:01',
                'updated_at' => '2019-11-11 12:43:01',
                'deleted_at' => NULL,
                'code' => 'NFRI',
            'description' => 'Normal (Friday)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 8,
                'dur_minute' => 30,
                'total_minute' => 510,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => '2019-11-11 12:52:02',
                'updated_at' => '2019-11-11 12:58:47',
                'deleted_at' => NULL,
                'code' => 'OFFD',
                'description' => 'Off Day',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 43570,
                'last_edited_by' => 43570,
                'deleted_by' => NULL,
                'bg_color' => '#e85edd',
                'font_color' => '#5731a6',
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => '2019-11-11 12:58:19',
                'updated_at' => '2019-11-11 12:58:19',
                'deleted_at' => NULL,
                'code' => 'RSTD',
                'description' => 'Rest Day',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#f36dc1',
                'font_color' => '#3235c0',
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => '2019-11-11 13:05:22',
                'updated_at' => '2019-11-11 13:05:22',
                'deleted_at' => NULL,
                'code' => 'NTHU',
            'description' => 'Normal (Thurs)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 8,
                'dur_minute' => 30,
                'total_minute' => 510,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => '2019-11-11 14:17:09',
                'updated_at' => '2019-11-11 14:17:09',
                'deleted_at' => NULL,
                'code' => 'NOR2',
                'description' => 'Normal WorkDay2',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 8,
                'dur_minute' => 30,
                'total_minute' => 510,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            7 => 
            array (
                'id' => 8,
                'created_at' => '2019-11-11 14:25:21',
                'updated_at' => '2019-11-11 14:33:35',
                'deleted_at' => '2019-11-11 14:33:35',
                'code' => 'HSAT',
            'description' => 'HalfDay (Sat)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 4,
                'dur_minute' => 25,
                'total_minute' => 265,
                'created_by' => 43570,
                'last_edited_by' => 43570,
                'deleted_by' => 43570,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            8 => 
            array (
                'id' => 9,
                'created_at' => '2019-11-11 14:28:34',
                'updated_at' => '2019-11-11 14:28:34',
                'deleted_at' => NULL,
                'code' => 'HTHU',
            'description' => 'HalfDay (Thur)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 4,
                'dur_minute' => 30,
                'total_minute' => 270,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            9 => 
            array (
                'id' => 10,
                'created_at' => '2019-11-11 14:41:31',
                'updated_at' => '2019-11-11 14:41:56',
                'deleted_at' => '2019-11-11 14:41:56',
                'code' => 'HSAT',
            'description' => 'HalfDay (Sat)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 4,
                'dur_minute' => 45,
                'total_minute' => 285,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => 43570,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            10 => 
            array (
                'id' => 11,
                'created_at' => '2019-11-11 14:43:00',
                'updated_at' => '2019-11-11 14:43:00',
                'deleted_at' => NULL,
                'code' => 'HSAT',
            'description' => 'HalfDay (Sat)',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 4,
                'dur_minute' => 15,
                'total_minute' => 255,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            11 => 
            array (
                'id' => 12,
                'created_at' => '2019-11-11 14:50:09',
                'updated_at' => '2019-11-11 14:50:09',
                'deleted_at' => NULL,
                'code' => 'NOR3',
                'description' => 'Normal WorkDay3',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 8,
                'dur_minute' => 15,
                'total_minute' => 495,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            12 => 
            array (
                'id' => 13,
                'created_at' => '2019-11-11 15:14:20',
                'updated_at' => '2019-11-11 15:14:20',
                'deleted_at' => NULL,
                'code' => 'NOR6',
                'description' => 'Normal WD GT&RD',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            13 => 
            array (
                'id' => 14,
                'created_at' => '2019-11-11 15:16:37',
                'updated_at' => '2019-11-11 15:16:37',
                'deleted_at' => NULL,
                'code' => 'NOR7',
                'description' => 'Normal WD VADS',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            14 => 
            array (
                'id' => 15,
                'created_at' => '2019-11-11 15:18:51',
                'updated_at' => '2019-11-11 15:18:51',
                'deleted_at' => NULL,
                'code' => 'NOR8',
                'description' => 'Normal WD TAB',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            15 => 
            array (
                'id' => 16,
                'created_at' => '2019-11-11 15:19:54',
                'updated_at' => '2019-11-11 15:19:54',
                'deleted_at' => NULL,
                'code' => 'NOR9',
                'description' => 'Normal WD TMIM',
                'is_work_day' => 1,
                'start_time' => '08:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            16 => 
            array (
                'id' => 17,
                'created_at' => '2019-11-11 15:21:18',
                'updated_at' => '2019-11-11 15:21:18',
                'deleted_at' => NULL,
                'code' => 'NOWD',
                'description' => 'Normal WD webe',
                'is_work_day' => 1,
                'start_time' => '09:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            17 => 
            array (
                'id' => 18,
                'created_at' => '2019-11-11 16:27:58',
                'updated_at' => '2019-11-11 16:27:58',
                'deleted_at' => NULL,
                'code' => 'NFRT',
            'description' => 'NormalFR(TSSSB)',
                'is_work_day' => 1,
                'start_time' => '09:00:00',
                'dur_hour' => 8,
                'dur_minute' => 30,
                'total_minute' => 510,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            18 => 
            array (
                'id' => 19,
                'created_at' => '2020-04-13 23:22:41',
                'updated_at' => '2020-04-13 23:22:41',
                'deleted_at' => NULL,
                'code' => 'PH',
                'description' => 'Public Holiday',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#00ff00',
                'font_color' => '#000000',
            ),
            19 => 
            array (
                'id' => 20,
                'created_at' => '2020-04-25 04:27:41',
                'updated_at' => '2020-04-25 04:28:26',
                'deleted_at' => NULL,
                'code' => 'Z05A',
            'description' => 'Z_05 (Afternoon)',
                'is_work_day' => 1,
                'start_time' => '20:00:00',
                'dur_hour' => 8,
                'dur_minute' => 0,
                'total_minute' => 480,
                'created_by' => 43570,
                'last_edited_by' => 43570,
                'deleted_by' => NULL,
                'bg_color' => '#00ff40',
                'font_color' => '#000000',
            ),
            20 => 
            array (
                'id' => 21,
                'created_at' => '2020-04-25 04:29:20',
                'updated_at' => '2020-04-25 04:29:45',
                'deleted_at' => NULL,
                'code' => 'Z05O',
            'description' => 'Z_05 (Off day)',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 43570,
                'last_edited_by' => 43570,
                'deleted_by' => NULL,
                'bg_color' => '#8080ff',
                'font_color' => '#000000',
            ),
            21 => 
            array (
                'id' => 22,
                'created_at' => '2020-04-25 04:31:09',
                'updated_at' => '2020-04-25 04:31:09',
                'deleted_at' => NULL,
                'code' => 'Z05R',
            'description' => 'Z_05 (Rest Day)',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffa579',
                'font_color' => '#000000',
            ),
            22 => 
            array (
                'id' => 23,
                'created_at' => '2020-04-25 09:07:24',
                'updated_at' => '2020-04-25 09:08:12',
                'deleted_at' => '2020-04-25 09:08:12',
                'code' => 'NOR1A',
            'description' => 'Normal WorkDay (Anjal jenis 1 8.00am-5.00pm)',
                'is_work_day' => 1,
                'start_time' => '08:00:00',
                'dur_hour' => 8,
                'dur_minute' => 0,
                'total_minute' => 480,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => 43570,
                'bg_color' => '#ff80ff',
                'font_color' => '#000000',
            ),
            23 => 
            array (
                'id' => 24,
                'created_at' => '2020-04-25 09:08:58',
                'updated_at' => '2020-04-25 09:08:58',
                'deleted_at' => NULL,
                'code' => 'NOR1A',
            'description' => 'Normal WorkDay (Anjal jenis A 8.00am-5.00pm)',
                'is_work_day' => 1,
                'start_time' => '08:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ff80ff',
                'font_color' => '#000000',
            ),
            24 => 
            array (
                'id' => 25,
                'created_at' => '2020-04-25 09:10:20',
                'updated_at' => '2020-04-25 09:10:20',
                'deleted_at' => NULL,
                'code' => 'NOR1B',
            'description' => 'Normal (Mon-Fri) - Waktu anjal (9.00am-6.00pm)',
                'is_work_day' => 1,
                'start_time' => '09:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#00ffff',
                'font_color' => '#000000',
            ),
            25 => 
            array (
                'id' => 26,
                'created_at' => '2020-05-03 09:09:59',
                'updated_at' => '2020-05-03 09:09:59',
                'deleted_at' => NULL,
                'code' => 'TEST1',
            'description' => 'Test1 (Test normal working hour at night)',
                'is_work_day' => 1,
                'start_time' => '20:30:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ff0000',
                'font_color' => '#000000',
            ),
            26 => 
            array (
                'id' => 27,
                'created_at' => '2020-05-04 11:16:20',
                'updated_at' => '2020-05-04 11:17:18',
                'deleted_at' => '2020-05-04 11:17:18',
                'code' => 'Z06M',
            'description' => '3 cycle shift(Morning)0700am-1500pm',
                'is_work_day' => 1,
                'start_time' => '07:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => 43570,
                'bg_color' => '#ff0000',
                'font_color' => '#000000',
            ),
            27 => 
            array (
                'id' => 28,
                'created_at' => '2020-05-04 11:17:55',
                'updated_at' => '2020-05-04 11:17:55',
                'deleted_at' => NULL,
                'code' => 'Z06M',
            'description' => '3 cycle shift(Morning)0700am-1500pm',
                'is_work_day' => 1,
                'start_time' => '07:00:00',
                'dur_hour' => 8,
                'dur_minute' => 0,
                'total_minute' => 480,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ff0000',
                'font_color' => '#000000',
            ),
            28 => 
            array (
                'id' => 29,
                'created_at' => '2020-05-04 11:19:51',
                'updated_at' => '2020-05-04 11:19:51',
                'deleted_at' => NULL,
                'code' => 'Z06A',
            'description' => '3 cycle shift(Afternoon)0700am-1500pm',
                'is_work_day' => 1,
                'start_time' => '15:00:00',
                'dur_hour' => 8,
                'dur_minute' => 0,
                'total_minute' => 480,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ff0000',
                'font_color' => '#000000',
            ),
            29 => 
            array (
                'id' => 30,
                'created_at' => '2020-05-04 11:23:38',
                'updated_at' => '2020-05-04 11:23:38',
                'deleted_at' => NULL,
                'code' => 'Z06N',
            'description' => '3 cycle shift (Night)2300pm-0700am',
                'is_work_day' => 1,
                'start_time' => '23:00:00',
                'dur_hour' => 8,
                'dur_minute' => 0,
                'total_minute' => 480,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ff0000',
                'font_color' => '#000000',
            ),
            30 => 
            array (
                'id' => 31,
                'created_at' => '2020-05-14 23:05:15',
                'updated_at' => '2020-05-14 23:06:19',
                'deleted_at' => '2020-05-14 23:06:19',
                'code' => 'Team1',
                'description' => 'Test 1-Demo',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 39868,
                'last_edited_by' => NULL,
                'deleted_by' => 39868,
                'bg_color' => '#ff8000',
                'font_color' => '#000000',
            ),
            31 => 
            array (
                'id' => 32,
                'created_at' => '2020-05-14 23:09:30',
                'updated_at' => '2020-05-14 23:09:58',
                'deleted_at' => '2020-05-14 23:09:58',
                'code' => 'Team1',
                'description' => 'Test 1-Demo',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 39868,
                'last_edited_by' => NULL,
                'deleted_by' => 39868,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            32 => 
            array (
                'id' => 33,
                'created_at' => '2020-05-14 23:13:24',
                'updated_at' => '2020-05-14 23:13:53',
                'deleted_at' => '2020-05-14 23:13:53',
                'code' => 'Team1',
                'description' => 'Test 1-Demo',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 39868,
                'last_edited_by' => NULL,
                'deleted_by' => 39868,
                'bg_color' => '#ff8000',
                'font_color' => '#000000',
            ),
            33 => 
            array (
                'id' => 34,
                'created_at' => '2020-05-14 23:16:19',
                'updated_at' => '2020-05-14 23:28:09',
                'deleted_at' => '2020-05-14 23:28:09',
                'code' => 'Team1',
                'description' => 'Test 1-Demo',
                'is_work_day' => 0,
                'start_time' => NULL,
                'dur_hour' => 0,
                'dur_minute' => 0,
                'total_minute' => 0,
                'created_by' => 39868,
                'last_edited_by' => NULL,
                'deleted_by' => 39868,
                'bg_color' => '#ff8000',
                'font_color' => '#000000',
            ),
            34 => 
            array (
                'id' => 35,
                'created_at' => '2020-05-15 08:00:06',
                'updated_at' => '2020-05-15 08:02:48',
                'deleted_at' => '2020-05-15 08:02:48',
                'code' => 'try',
                'description' => 'try',
                'is_work_day' => 1,
                'start_time' => '09:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 39868,
                'last_edited_by' => NULL,
                'deleted_by' => 39868,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
            35 => 
            array (
                'id' => 36,
                'created_at' => '2020-05-15 12:46:27',
                'updated_at' => '2020-05-15 12:46:27',
                'deleted_at' => NULL,
                'code' => 'Team1',
                'description' => 'Test 1-Demo',
                'is_work_day' => 1,
                'start_time' => '09:00:00',
                'dur_hour' => 8,
                'dur_minute' => 0,
                'total_minute' => 480,
                'created_by' => 39868,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ff8000',
                'font_color' => '#000000',
            ),
            36 => 
            array (
                'id' => 37,
                'created_at' => '2020-05-18 16:36:05',
                'updated_at' => '2020-05-18 16:36:05',
                'deleted_at' => NULL,
                'code' => 'test',
                'description' => 'test',
                'is_work_day' => 1,
                'start_time' => '09:00:00',
                'dur_hour' => 9,
                'dur_minute' => 0,
                'total_minute' => 540,
                'created_by' => 43570,
                'last_edited_by' => NULL,
                'deleted_by' => NULL,
                'bg_color' => '#ffffff',
                'font_color' => '#000000',
            ),
        ));
        
        
    }
}