<?php

use Illuminate\Database\Seeder;

class HolidayLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('holiday_logs')->delete();
        
        \DB::table('holiday_logs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'holiday_id' => 1,
                'descr' => 'New Year',
                'dt' => '2016-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 19562,
                'action' => 'INSERT',
                'created_at' => '2019-11-18 17:16:40',
                'updated_at' => '2019-11-18 17:16:40',
            ),
            1 => 
            array (
                'id' => 2,
                'holiday_id' => 2,
                'descr' => 'New Year',
                'dt' => '2018-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 19562,
                'action' => 'INSERT',
                'created_at' => '2019-11-18 17:18:05',
                'updated_at' => '2019-11-18 17:18:05',
            ),
            2 => 
            array (
                'id' => 3,
                'holiday_id' => 3,
                'descr' => 'New Year',
                'dt' => '2019-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 19562,
                'action' => 'INSERT',
                'created_at' => '2019-11-18 17:22:05',
                'updated_at' => '2019-11-18 17:22:05',
            ),
            3 => 
            array (
                'id' => 4,
                'holiday_id' => 4,
                'descr' => 'Thaipusam Day',
                'dt' => '2019-01-21',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:40:37',
                'updated_at' => '2019-11-21 09:40:37',
            ),
            4 => 
            array (
                'id' => 5,
                'holiday_id' => 5,
            'descr' => 'Federal Territory Day (MY)',
                'dt' => '2019-02-01',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:41:45',
                'updated_at' => '2019-11-21 09:41:45',
            ),
            5 => 
            array (
                'id' => 6,
                'holiday_id' => 6,
            'descr' => 'Chinese New Year Day 1 (MY)',
                'dt' => '2019-02-05',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:42:38',
                'updated_at' => '2019-11-21 09:42:38',
            ),
            6 => 
            array (
                'id' => 7,
                'holiday_id' => 7,
            'descr' => 'Labour Day (MY)',
                'dt' => '2019-05-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:43:47',
                'updated_at' => '2019-11-21 09:43:47',
            ),
            7 => 
            array (
                'id' => 8,
                'holiday_id' => 7,
            'descr' => 'Labour Day (MY)',
                'dt' => '2019-05-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 09:43:54',
                'updated_at' => '2019-11-21 09:43:54',
            ),
            8 => 
            array (
                'id' => 9,
                'holiday_id' => 8,
            'descr' => 'Wesak Day (MY)',
                'dt' => '2019-05-19',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:44:54',
                'updated_at' => '2019-11-21 09:44:54',
            ),
            9 => 
            array (
                'id' => 10,
                'holiday_id' => 9,
            'descr' => 'Hari Raya Puasa Day 2 (MY)',
                'dt' => '2019-06-06',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:46:07',
                'updated_at' => '2019-11-21 09:46:07',
            ),
            10 => 
            array (
                'id' => 11,
                'holiday_id' => 10,
            'descr' => 'Hari Raya Qurban Day 1 (MY)',
                'dt' => '2019-08-11',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:47:51',
                'updated_at' => '2019-11-21 09:47:51',
            ),
            11 => 
            array (
                'id' => 12,
                'holiday_id' => 11,
            'descr' => 'National Holiday (MY)',
                'dt' => '2019-08-31',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:48:20',
                'updated_at' => '2019-11-21 09:48:20',
            ),
            12 => 
            array (
                'id' => 13,
                'holiday_id' => 12,
            'descr' => 'Awal Muharam- Maal Hijrah (MY)',
                'dt' => '2019-09-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:53:34',
                'updated_at' => '2019-11-21 09:53:34',
            ),
            13 => 
            array (
                'id' => 14,
                'holiday_id' => 13,
                'descr' => 'Malaysia Day',
                'dt' => '2019-09-16',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:54:01',
                'updated_at' => '2019-11-21 09:54:01',
            ),
            14 => 
            array (
                'id' => 15,
                'holiday_id' => 14,
            'descr' => 'Deepavali Day  (MY)',
                'dt' => '2019-10-27',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 09:54:26',
                'updated_at' => '2019-11-21 09:54:26',
            ),
            15 => 
            array (
                'id' => 16,
                'holiday_id' => 15,
            'descr' => 'Deepavali Day  (MY)',
                'dt' => '2019-11-09',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:01:11',
                'updated_at' => '2019-11-21 10:01:11',
            ),
            16 => 
            array (
                'id' => 17,
                'holiday_id' => 15,
            'descr' => 'Deepavali Day  (MY)',
                'dt' => '2019-11-09',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:01:50',
                'updated_at' => '2019-11-21 10:01:50',
            ),
            17 => 
            array (
                'id' => 18,
                'holiday_id' => 15,
            'descr' => 'Deepavali Day  (MY)',
                'dt' => '2019-11-09',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:02:04',
                'updated_at' => '2019-11-21 10:02:04',
            ),
            18 => 
            array (
                'id' => 19,
                'holiday_id' => 15,
            'descr' => 'Deepavali Day  (MY)',
                'dt' => '2019-11-09',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:02:43',
                'updated_at' => '2019-11-21 10:02:43',
            ),
            19 => 
            array (
                'id' => 20,
                'holiday_id' => 15,
            'descr' => 'Deepavali Day  (MY)',
                'dt' => '2019-11-09',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:03:36',
                'updated_at' => '2019-11-21 10:03:36',
            ),
            20 => 
            array (
                'id' => 21,
                'holiday_id' => 15,
            'descr' => 'Deepavali Day  (MY)',
                'dt' => '2019-11-09',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:03:49',
                'updated_at' => '2019-11-21 10:03:49',
            ),
            21 => 
            array (
                'id' => 22,
                'holiday_id' => 16,
            'descr' => 'Christmas Day (MY)',
                'dt' => '2019-12-25',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:08:39',
                'updated_at' => '2019-11-21 10:08:39',
            ),
            22 => 
            array (
                'id' => 23,
                'holiday_id' => 4,
                'descr' => 'Thaipusam Day',
                'dt' => '2019-01-21',
                'guarantee_flag' => 0,
                'states' => '"WP","LB","PJ"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:13:28',
                'updated_at' => '2019-11-21 10:13:28',
            ),
            23 => 
            array (
                'id' => 24,
                'holiday_id' => 5,
            'descr' => 'Federal Territory Day (MY)',
                'dt' => '2019-02-01',
                'guarantee_flag' => 0,
                'states' => '"WP","LB","PJ"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:14:01',
                'updated_at' => '2019-11-21 10:14:01',
            ),
            24 => 
            array (
                'id' => 25,
                'holiday_id' => 6,
            'descr' => 'Chinese New Year Day 1 (MY)',
                'dt' => '2019-02-05',
                'guarantee_flag' => 0,
                'states' => '"WP","LB","PJ"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:14:15',
                'updated_at' => '2019-11-21 10:14:15',
            ),
            25 => 
            array (
                'id' => 26,
                'holiday_id' => 8,
            'descr' => 'Wesak Day (MY)',
                'dt' => '2019-05-19',
                'guarantee_flag' => 0,
                'states' => '"WP","LB","PJ"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:14:30',
                'updated_at' => '2019-11-21 10:14:30',
            ),
            26 => 
            array (
                'id' => 27,
                'holiday_id' => 17,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:31:26',
                'updated_at' => '2019-11-21 10:31:26',
            ),
            27 => 
            array (
                'id' => 28,
                'holiday_id' => 18,
            'descr' => 'Chinese New Year Day 1 (MY)',
                'dt' => '2020-01-25',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:39:50',
                'updated_at' => '2019-11-21 10:39:50',
            ),
            28 => 
            array (
                'id' => 29,
                'holiday_id' => 19,
            'descr' => 'Chinese New Year Day 1 (MY)',
                'dt' => '2020-01-26',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:41:52',
                'updated_at' => '2019-11-21 10:41:52',
            ),
            29 => 
            array (
                'id' => 30,
                'holiday_id' => 19,
            'descr' => 'Chinese New Year Day 1 (MY)',
                'dt' => '2020-01-26',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 10:42:22',
                'updated_at' => '2019-11-21 10:42:22',
            ),
            30 => 
            array (
                'id' => 31,
                'holiday_id' => 20,
            'descr' => 'Federal Territory Day (MY)',
                'dt' => '2010-02-01',
                'guarantee_flag' => 0,
                'states' => '"LB","PJ","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:43:07',
                'updated_at' => '2019-11-21 10:43:07',
            ),
            31 => 
            array (
                'id' => 32,
                'holiday_id' => 21,
                'descr' => 'Thaipusam Day',
                'dt' => '2020-02-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:49:40',
                'updated_at' => '2019-11-21 10:49:40',
            ),
            32 => 
            array (
                'id' => 33,
                'holiday_id' => 22,
            'descr' => 'Labour Day (MY)',
                'dt' => '2020-05-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:50:29',
                'updated_at' => '2019-11-21 10:50:29',
            ),
            33 => 
            array (
                'id' => 34,
                'holiday_id' => 23,
            'descr' => 'Wesak Day (MY)',
                'dt' => '2020-05-07',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:51:48',
                'updated_at' => '2019-11-21 10:51:48',
            ),
            34 => 
            array (
                'id' => 35,
                'holiday_id' => 24,
                'descr' => 'Nuzul Al-Quran Day Sun',
                'dt' => '2020-05-10',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:52:55',
                'updated_at' => '2019-11-21 10:52:55',
            ),
            35 => 
            array (
                'id' => 36,
                'holiday_id' => 25,
            'descr' => 'Hari Raya Puasa Day 1 (MY) Sun',
                'dt' => '2020-05-24',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:57:07',
                'updated_at' => '2019-11-21 10:57:07',
            ),
            36 => 
            array (
                'id' => 37,
                'holiday_id' => 26,
            'descr' => 'Hari Raya Puasa Day 2 (MY)',
                'dt' => '2020-05-25',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 10:57:43',
                'updated_at' => '2019-11-21 10:57:43',
            ),
            37 => 
            array (
                'id' => 38,
                'holiday_id' => 27,
            'descr' => 'Hari Raya Puasa Day 1 (MY) Sun , moved',
                'dt' => '2020-05-26',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:00:34',
                'updated_at' => '2019-11-21 11:00:34',
            ),
            38 => 
            array (
                'id' => 39,
                'holiday_id' => 28,
                'descr' => 'Hari Keputeraan YDP Agong',
                'dt' => '2020-06-06',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:01:17',
                'updated_at' => '2019-11-21 11:01:17',
            ),
            39 => 
            array (
                'id' => 40,
                'holiday_id' => 29,
            'descr' => 'Hari Raya Qurban Day 1 (MY)',
                'dt' => '2020-07-31',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:02:17',
                'updated_at' => '2019-11-21 11:02:17',
            ),
            40 => 
            array (
                'id' => 41,
                'holiday_id' => 30,
            'descr' => 'Awal Muharam- Maal Hijrah (MY)',
                'dt' => '2020-08-20',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:02:59',
                'updated_at' => '2019-11-21 11:02:59',
            ),
            41 => 
            array (
                'id' => 42,
                'holiday_id' => 31,
            'descr' => 'National Holiday (MY)',
                'dt' => '2020-08-31',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:03:35',
                'updated_at' => '2019-11-21 11:03:35',
            ),
            42 => 
            array (
                'id' => 43,
                'holiday_id' => 32,
                'descr' => 'Malaysia Day',
                'dt' => '2020-09-16',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:04:19',
                'updated_at' => '2019-11-21 11:04:19',
            ),
            43 => 
            array (
                'id' => 44,
                'holiday_id' => 33,
            'descr' => 'Prophet Muhammad\'s B\'day (MY)',
                'dt' => '2020-10-29',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:05:43',
                'updated_at' => '2019-11-21 11:05:43',
            ),
            44 => 
            array (
                'id' => 45,
                'holiday_id' => 34,
            'descr' => 'Deepavali Day  (MY)',
                'dt' => '2020-11-14',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:07:00',
                'updated_at' => '2019-11-21 11:07:00',
            ),
            45 => 
            array (
                'id' => 46,
                'holiday_id' => 35,
            'descr' => 'Christmas Day (MY)',
                'dt' => '2020-12-25',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:07:44',
                'updated_at' => '2019-11-21 11:07:44',
            ),
            46 => 
            array (
                'id' => 47,
                'holiday_id' => 17,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 11:11:44',
                'updated_at' => '2019-11-21 11:11:44',
            ),
            47 => 
            array (
                'id' => 48,
                'holiday_id' => 3,
                'descr' => 'New Year',
                'dt' => '2019-01-01',
                'guarantee_flag' => 0,
                'states' => '"KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 19562,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 11:11:52',
                'updated_at' => '2019-11-21 11:11:52',
            ),
            48 => 
            array (
                'id' => 49,
                'holiday_id' => 3,
                'descr' => 'New Year',
                'dt' => '2019-01-01',
                'guarantee_flag' => 0,
                'states' => '"KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 19562,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 11:12:05',
                'updated_at' => '2019-11-21 11:12:05',
            ),
            49 => 
            array (
                'id' => 50,
                'holiday_id' => 36,
                'descr' => 'Birthday of Sultan Johor MY',
                'dt' => '2019-03-23',
                'guarantee_flag' => 0,
                'states' => '"JH"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:13:02',
                'updated_at' => '2019-11-21 11:13:02',
            ),
            50 => 
            array (
                'id' => 51,
                'holiday_id' => 37,
                'descr' => 'Hari Hol Sultan Iskandar',
                'dt' => '2020-10-05',
                'guarantee_flag' => 0,
                'states' => '"JH"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:22:53',
                'updated_at' => '2019-11-21 11:22:53',
            ),
            51 => 
            array (
                'id' => 52,
                'holiday_id' => 38,
                'descr' => 'Birthday of Sultan Johor MY',
                'dt' => '2020-03-23',
                'guarantee_flag' => 0,
                'states' => '"JH"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:26:50',
                'updated_at' => '2019-11-21 11:26:50',
            ),
            52 => 
            array (
                'id' => 53,
                'holiday_id' => 39,
                'descr' => 'Hari Hol Sultan Iskandar',
                'dt' => '2020-09-24',
                'guarantee_flag' => 0,
                'states' => '"JH"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:31:02',
                'updated_at' => '2019-11-21 11:31:02',
            ),
            53 => 
            array (
                'id' => 54,
                'holiday_id' => 3,
                'descr' => 'New Year',
                'dt' => '2019-01-01',
                'guarantee_flag' => 0,
                'states' => '"KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 19562,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 11:32:42',
                'updated_at' => '2019-11-21 11:32:42',
            ),
            54 => 
            array (
                'id' => 55,
                'holiday_id' => 40,
                'descr' => 'Birthday of Sultan Kedah',
                'dt' => '2019-01-20',
                'guarantee_flag' => 0,
                'states' => '"KH"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:33:23',
                'updated_at' => '2019-11-21 11:33:23',
            ),
            55 => 
            array (
                'id' => 56,
                'holiday_id' => 41,
                'descr' => 'Israk and Mikraj',
                'dt' => '2019-04-03',
                'guarantee_flag' => 0,
                'states' => '"KH"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:35:24',
                'updated_at' => '2019-11-21 11:35:24',
            ),
            56 => 
            array (
                'id' => 57,
                'holiday_id' => 8,
            'descr' => 'Wesak Day (MY)',
                'dt' => '2019-05-19',
                'guarantee_flag' => 0,
                'states' => '"WP","LB","PJ","JH","KH","KT","ML","NS","PG","PK","PP","PR","SB","SN","SR","TG"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 11:36:13',
                'updated_at' => '2019-11-21 11:36:13',
            ),
            57 => 
            array (
                'id' => 58,
                'holiday_id' => 3,
                'descr' => 'New Year',
                'dt' => '2019-01-01',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 19562,
                'action' => 'UPDATE',
                'created_at' => '2019-11-21 11:43:58',
                'updated_at' => '2019-11-21 11:43:58',
            ),
            58 => 
            array (
                'id' => 59,
                'holiday_id' => 42,
                'descr' => 'Sultan Kelantan Birthday Day 1',
                'dt' => '2019-11-11',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:44:57',
                'updated_at' => '2019-11-21 11:44:57',
            ),
            59 => 
            array (
                'id' => 60,
                'holiday_id' => 43,
                'descr' => 'Sultan Kelantan Birthday Day 2',
                'dt' => '2019-11-12',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2019-11-21 11:45:34',
                'updated_at' => '2019-11-21 11:45:34',
            ),
            60 => 
            array (
                'id' => 61,
                'holiday_id' => 44,
            'descr' => 'Chinese New Year Day 1 (MY) Sat Replacement',
                'dt' => '2020-01-24',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","WP"',
                'update_by' => 19021,
                'action' => 'INSERT',
                'created_at' => '2020-01-06 13:21:03',
                'updated_at' => '2020-01-06 13:21:03',
            ),
            61 => 
            array (
                'id' => 62,
                'holiday_id' => 19,
            'descr' => 'Chinese New Year Day 2 (MY)',
                'dt' => '2020-01-26',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 19021,
                'action' => 'UPDATE',
                'created_at' => '2020-01-06 13:21:25',
                'updated_at' => '2020-01-06 13:21:25',
            ),
            62 => 
            array (
                'id' => 63,
                'holiday_id' => 17,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-02 11:47:55',
                'updated_at' => '2020-04-02 11:47:55',
            ),
            63 => 
            array (
                'id' => 64,
                'holiday_id' => 17,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 11:48:52',
                'updated_at' => '2020-04-02 11:48:52',
            ),
            64 => 
            array (
                'id' => 65,
                'holiday_id' => 45,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 11:49:49',
                'updated_at' => '2020-04-02 11:49:49',
            ),
            65 => 
            array (
                'id' => 66,
                'holiday_id' => 46,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 11:51:15',
                'updated_at' => '2020-04-02 11:51:15',
            ),
            66 => 
            array (
                'id' => 67,
                'holiday_id' => 46,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","PG","PK","PR","SB","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-02 11:52:01',
                'updated_at' => '2020-04-02 11:52:01',
            ),
            67 => 
            array (
                'id' => 68,
                'holiday_id' => 46,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","PG","PK","PR","SB","SR","TG","WP","NS","PJ","PP","SN"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-02 12:12:00',
                'updated_at' => '2020-04-02 12:12:00',
            ),
            68 => 
            array (
                'id' => 69,
                'holiday_id' => 45,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 12:19:24',
                'updated_at' => '2020-04-02 12:19:24',
            ),
            69 => 
            array (
                'id' => 70,
                'holiday_id' => 47,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 12:20:16',
                'updated_at' => '2020-04-02 12:20:16',
            ),
            70 => 
            array (
                'id' => 71,
                'holiday_id' => 35,
            'descr' => 'Christmas Day (MY)',
                'dt' => '2020-12-25',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 12:25:27',
                'updated_at' => '2020-04-02 12:25:27',
            ),
            71 => 
            array (
                'id' => 72,
                'holiday_id' => 48,
            'descr' => 'Christmas Day (MY)',
                'dt' => '2020-12-25',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 12:25:52',
                'updated_at' => '2020-04-02 12:25:52',
            ),
            72 => 
            array (
                'id' => 73,
                'holiday_id' => 49,
            'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-04-01',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 15:29:47',
                'updated_at' => '2020-04-02 15:29:47',
            ),
            73 => 
            array (
                'id' => 74,
                'holiday_id' => 49,
            'descr' => 'Cuti Peristiwa - Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-04-01',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-02 15:30:29',
                'updated_at' => '2020-04-02 15:30:29',
            ),
            74 => 
            array (
                'id' => 75,
                'holiday_id' => 49,
            'descr' => 'Cuti Peristiwa - Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-04-01',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 15:30:48',
                'updated_at' => '2020-04-02 15:30:48',
            ),
            75 => 
            array (
                'id' => 76,
                'holiday_id' => 46,
            'descr' => 'Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-02 15:32:06',
                'updated_at' => '2020-04-02 15:32:06',
            ),
            76 => 
            array (
                'id' => 77,
                'holiday_id' => 46,
                'descr' => 'Cuti Peristiwa Final  Piala Malaysia',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"KT","JH","KH","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-02 15:33:21',
                'updated_at' => '2020-04-02 15:33:21',
            ),
            77 => 
            array (
                'id' => 78,
                'holiday_id' => 46,
                'descr' => 'Cuti Peristiwa Final  Piala Malaysia',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"KT","JH","KH","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 15:33:45',
                'updated_at' => '2020-04-02 15:33:45',
            ),
            78 => 
            array (
                'id' => 79,
                'holiday_id' => 50,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 15:34:31',
                'updated_at' => '2020-04-02 15:34:31',
            ),
            79 => 
            array (
                'id' => 80,
                'holiday_id' => 50,
                'descr' => 'Cuti Kuarantin COVID19',
                'dt' => '2020-08-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-02 15:35:23',
                'updated_at' => '2020-04-02 15:35:23',
            ),
            80 => 
            array (
                'id' => 81,
                'holiday_id' => 50,
                'descr' => 'Cuti Kuarantin COVID19',
                'dt' => '2020-08-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 15:35:40',
                'updated_at' => '2020-04-02 15:35:40',
            ),
            81 => 
            array (
                'id' => 82,
                'holiday_id' => 51,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 15:36:43',
                'updated_at' => '2020-04-02 15:36:43',
            ),
            82 => 
            array (
                'id' => 83,
                'holiday_id' => 51,
                'descr' => 'Cuti Kuarantin COVID19',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-02 15:37:24',
                'updated_at' => '2020-04-02 15:37:24',
            ),
            83 => 
            array (
                'id' => 84,
                'holiday_id' => 51,
                'descr' => 'Cuti Kuarantin COVID19',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 15:37:37',
                'updated_at' => '2020-04-02 15:37:37',
            ),
            84 => 
            array (
                'id' => 85,
                'holiday_id' => 52,
            'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-08-01',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 15:38:29',
                'updated_at' => '2020-04-02 15:38:29',
            ),
            85 => 
            array (
                'id' => 86,
                'holiday_id' => 52,
            'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-08-01',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 15:39:53',
                'updated_at' => '2020-04-02 15:39:53',
            ),
            86 => 
            array (
                'id' => 87,
                'holiday_id' => 53,
            'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-08-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 15:41:19',
                'updated_at' => '2020-04-02 15:41:19',
            ),
            87 => 
            array (
                'id' => 88,
                'holiday_id' => 53,
            'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-08-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-02 15:42:17',
                'updated_at' => '2020-04-02 15:42:17',
            ),
            88 => 
            array (
                'id' => 89,
                'holiday_id' => 54,
                'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-02 16:15:50',
                'updated_at' => '2020-04-02 16:15:50',
            ),
            89 => 
            array (
                'id' => 90,
                'holiday_id' => 48,
            'descr' => 'Christmas Day (MY)',
                'dt' => '2020-12-25',
                'guarantee_flag' => 0,
                'states' => '"KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-03 12:10:53',
                'updated_at' => '2020-04-03 12:10:53',
            ),
            90 => 
            array (
                'id' => 91,
                'holiday_id' => 48,
            'descr' => 'Christmas Day (MY)',
                'dt' => '2020-12-25',
                'guarantee_flag' => 0,
                'states' => '"KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP","JH"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-03 12:12:30',
                'updated_at' => '2020-04-03 12:12:30',
            ),
            91 => 
            array (
                'id' => 92,
                'holiday_id' => 55,
                'descr' => 'ITAAD HOLIDAY',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-03 14:04:08',
                'updated_at' => '2020-04-03 14:04:08',
            ),
            92 => 
            array (
                'id' => 93,
                'holiday_id' => 55,
                'descr' => 'ITAAD HOLIDAY',
                'dt' => '2020-04-15',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-03 14:07:01',
                'updated_at' => '2020-04-03 14:07:01',
            ),
            93 => 
            array (
                'id' => 94,
                'holiday_id' => 55,
                'descr' => 'ITAAD HOLIDAY',
                'dt' => '2020-04-15',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-03 14:07:51',
                'updated_at' => '2020-04-03 14:07:51',
            ),
            94 => 
            array (
                'id' => 95,
                'holiday_id' => 56,
                'descr' => 'ITAAD HOLIDAY',
                'dt' => '2020-04-15',
                'guarantee_flag' => 0,
                'states' => '',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-03 14:08:15',
                'updated_at' => '2020-04-03 14:08:15',
            ),
            95 => 
            array (
                'id' => 96,
                'holiday_id' => 56,
                'descr' => 'ITAAD HOLIDAY',
                'dt' => '2020-04-15',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-03 14:11:49',
                'updated_at' => '2020-04-03 14:11:49',
            ),
            96 => 
            array (
                'id' => 97,
                'holiday_id' => 56,
                'descr' => 'ITAAD HOLIDAY',
                'dt' => '2020-04-15',
                'guarantee_flag' => 0,
                'states' => '"WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-03 14:13:18',
                'updated_at' => '2020-04-03 14:13:18',
            ),
            97 => 
            array (
                'id' => 98,
                'holiday_id' => 47,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KT"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-03 16:38:56',
                'updated_at' => '2020-04-03 16:38:56',
            ),
            98 => 
            array (
                'id' => 99,
                'holiday_id' => 57,
                'descr' => 'AMIRAH',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"KT","ML"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 11:36:40',
                'updated_at' => '2020-04-08 11:36:40',
            ),
            99 => 
            array (
                'id' => 100,
                'holiday_id' => 57,
                'descr' => 'AMIRAH',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"KT","ML"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 11:36:47',
                'updated_at' => '2020-04-08 11:36:47',
            ),
            100 => 
            array (
                'id' => 101,
                'holiday_id' => 58,
                'descr' => 'test',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 13:14:58',
                'updated_at' => '2020-04-08 13:14:58',
            ),
            101 => 
            array (
                'id' => 102,
                'holiday_id' => 58,
                'descr' => 'test',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-08 13:15:50',
                'updated_at' => '2020-04-08 13:15:50',
            ),
            102 => 
            array (
                'id' => 103,
                'holiday_id' => 59,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 15:31:44',
                'updated_at' => '2020-04-08 15:31:44',
            ),
            103 => 
            array (
                'id' => 104,
                'holiday_id' => 58,
                'descr' => 'test',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 15:32:05',
                'updated_at' => '2020-04-08 15:32:05',
            ),
            104 => 
            array (
                'id' => 105,
                'holiday_id' => 59,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-08 15:32:35',
                'updated_at' => '2020-04-08 15:32:35',
            ),
            105 => 
            array (
                'id' => 106,
                'holiday_id' => 54,
                'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 15:33:35',
                'updated_at' => '2020-04-08 15:33:35',
            ),
            106 => 
            array (
                'id' => 107,
                'holiday_id' => 59,
                'descr' => 'Birthday o Sultan Kelantan',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-08 15:47:51',
                'updated_at' => '2020-04-08 15:47:51',
            ),
            107 => 
            array (
                'id' => 108,
                'holiday_id' => 59,
                'descr' => 'Birthday o Sultan Kelantan',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 15:48:25',
                'updated_at' => '2020-04-08 15:48:25',
            ),
            108 => 
            array (
                'id' => 109,
                'holiday_id' => 60,
                'descr' => 'Birthday of Zati',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 15:49:19',
                'updated_at' => '2020-04-08 15:49:19',
            ),
            109 => 
            array (
                'id' => 110,
                'holiday_id' => 60,
                'descr' => 'Birthday of Zati',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 15:49:50',
                'updated_at' => '2020-04-08 15:49:50',
            ),
            110 => 
            array (
                'id' => 111,
                'holiday_id' => 61,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 15:52:55',
                'updated_at' => '2020-04-08 15:52:55',
            ),
            111 => 
            array (
                'id' => 112,
                'holiday_id' => 62,
            'descr' => 'New Year (MY)',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 15:54:19',
                'updated_at' => '2020-04-08 15:54:19',
            ),
            112 => 
            array (
                'id' => 113,
                'holiday_id' => 62,
            'descr' => 'New Year (MY)',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 15:54:47',
                'updated_at' => '2020-04-08 15:54:47',
            ),
            113 => 
            array (
                'id' => 114,
                'holiday_id' => 61,
                'descr' => 'Amirah\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-08 15:55:12',
                'updated_at' => '2020-04-08 15:55:12',
            ),
            114 => 
            array (
                'id' => 115,
                'holiday_id' => 61,
                'descr' => 'YDP Agong\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-08 15:56:02',
                'updated_at' => '2020-04-08 15:56:02',
            ),
            115 => 
            array (
                'id' => 116,
                'holiday_id' => 63,
                'descr' => 'zati birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 15:56:51',
                'updated_at' => '2020-04-08 15:56:51',
            ),
            116 => 
            array (
                'id' => 117,
                'holiday_id' => 63,
                'descr' => 'zati birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 15:57:01',
                'updated_at' => '2020-04-08 15:57:01',
            ),
            117 => 
            array (
                'id' => 118,
                'holiday_id' => 61,
                'descr' => 'YDP Agong Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-08 15:57:46',
                'updated_at' => '2020-04-08 15:57:46',
            ),
            118 => 
            array (
                'id' => 119,
                'holiday_id' => 61,
                'descr' => 'YDP Agong Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 15:57:59',
                'updated_at' => '2020-04-08 15:57:59',
            ),
            119 => 
            array (
                'id' => 120,
                'holiday_id' => 64,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 16:02:00',
                'updated_at' => '2020-04-08 16:02:00',
            ),
            120 => 
            array (
                'id' => 121,
                'holiday_id' => 65,
            'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-08 16:02:35',
                'updated_at' => '2020-04-08 16:02:35',
            ),
            121 => 
            array (
                'id' => 122,
                'holiday_id' => 65,
            'descr' => 'Cuti Peristiwa Sempena Juara Piala Malaysia (Kelantan)',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"KT"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 16:02:47',
                'updated_at' => '2020-04-08 16:02:47',
            ),
            122 => 
            array (
                'id' => 123,
                'holiday_id' => 64,
                'descr' => 'Zati Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-08 16:03:03',
                'updated_at' => '2020-04-08 16:03:03',
            ),
            123 => 
            array (
                'id' => 124,
                'holiday_id' => 64,
                'descr' => 'Zati Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 16:03:16',
                'updated_at' => '2020-04-08 16:03:16',
            ),
            124 => 
            array (
                'id' => 125,
                'holiday_id' => 48,
            'descr' => 'Christmas Day (MY)',
                'dt' => '2020-12-25',
                'guarantee_flag' => 0,
                'states' => '"KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP","JH"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-08 17:22:06',
                'updated_at' => '2020-04-08 17:22:06',
            ),
            125 => 
            array (
                'id' => 126,
                'holiday_id' => 47,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-03',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KT"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-08 17:35:47',
                'updated_at' => '2020-04-08 17:35:47',
            ),
            126 => 
            array (
                'id' => 127,
                'holiday_id' => 66,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'INSERT',
                'created_at' => '2020-04-09 08:39:10',
                'updated_at' => '2020-04-09 08:39:10',
            ),
            127 => 
            array (
                'id' => 128,
                'holiday_id' => 66,
                'descr' => 'Zati\'s Birthday',
                'dt' => '2020-08-08',
                'guarantee_flag' => 0,
                'states' => '"JH","KH","KT","LB","ML","NS","PG","PJ","PK","PP","PR","SB","SN","SR","TG","WP"',
                'update_by' => 43570,
                'action' => 'DESTROY',
                'created_at' => '2020-04-09 08:39:26',
                'updated_at' => '2020-04-09 08:39:26',
            ),
            128 => 
            array (
                'id' => 129,
                'holiday_id' => 21,
                'descr' => 'Thaipusam Day',
                'dt' => '2020-02-08',
                'guarantee_flag' => 0,
                'states' => '"KH","LB","ML","NS","PG","PJ","PK","PP","PR","SN","TG","WP"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-09 08:56:09',
                'updated_at' => '2020-04-09 08:56:09',
            ),
            129 => 
            array (
                'id' => 130,
                'holiday_id' => 47,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-03',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KT","JH","KH","PR","TG"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-09 08:59:21',
                'updated_at' => '2020-04-09 08:59:21',
            ),
            130 => 
            array (
                'id' => 131,
                'holiday_id' => 47,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KT","JH","KH","PR","TG"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-09 08:59:57',
                'updated_at' => '2020-04-09 08:59:57',
            ),
            131 => 
            array (
                'id' => 132,
                'holiday_id' => 47,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KH","PR","TG"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-09 09:00:42',
                'updated_at' => '2020-04-09 09:00:42',
            ),
            132 => 
            array (
                'id' => 133,
                'holiday_id' => 47,
            'descr' => 'New Year (MY)',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KH","PR","TG","JH"',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-10 15:28:42',
                'updated_at' => '2020-04-10 15:28:42',
            ),
            133 => 
            array (
                'id' => 134,
                'holiday_id' => 67,
                'descr' => 'jjj',
                'dt' => '2020-01-01',
                'guarantee_flag' => 0,
                'states' => '',
                'update_by' => 15076,
                'action' => 'INSERT',
                'created_at' => '2020-04-13 09:12:08',
                'updated_at' => '2020-04-13 09:12:08',
            ),
            134 => 
            array (
                'id' => 135,
                'holiday_id' => 44,
            'descr' => 'Chinese New Year Day 1 (MY) Sat Replacement',
                'dt' => '2020-01-24',
                'guarantee_flag' => 0,
                'states' => '',
                'update_by' => 15076,
                'action' => 'UPDATE',
                'created_at' => '2020-04-13 09:53:40',
                'updated_at' => '2020-04-13 09:53:40',
            ),
            135 => 
            array (
                'id' => 136,
                'holiday_id' => 21,
                'descr' => 'Thaipusam Day',
                'dt' => '2020-02-08',
                'guarantee_flag' => 0,
                'states' => '',
                'update_by' => 43570,
                'action' => 'UPDATE',
                'created_at' => '2020-04-14 13:39:42',
                'updated_at' => '2020-04-14 13:39:42',
            ),
            136 => 
            array (
                'id' => 137,
                'holiday_id' => 47,
                'descr' => 'New Year (MY',
                    'dt' => '2020-01-01',
                    'guarantee_flag' => 0,
                    'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KH","PR","TG","JH"',
                    'update_by' => 15076,
                    'action' => 'UPDATE',
                    'created_at' => '2020-04-14 15:56:07',
                    'updated_at' => '2020-04-14 15:56:07',
                ),
                137 => 
                array (
                    'id' => 138,
                    'holiday_id' => 47,
                'descr' => 'New Year (us)',
                    'dt' => '2020-01-01',
                    'guarantee_flag' => 0,
                    'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KH","PR","TG","JH"',
                    'update_by' => 15076,
                    'action' => 'UPDATE',
                    'created_at' => '2020-04-14 15:56:31',
                    'updated_at' => '2020-04-14 15:56:31',
                ),
                138 => 
                array (
                    'id' => 139,
                    'holiday_id' => 47,
                'descr' => 'New Year (MY)',
                    'dt' => '2020-01-01',
                    'guarantee_flag' => 0,
                    'states' => '"LB","ML","NS","PG","PJ","PK","PP","SB","SN","SR","WP","KH","PR","TG","JH"',
                    'update_by' => 15076,
                    'action' => 'UPDATE',
                    'created_at' => '2020-04-14 15:56:49',
                    'updated_at' => '2020-04-14 15:56:49',
                ),
                139 => 
                array (
                    'id' => 140,
                    'holiday_id' => 68,
                    'descr' => 'ITAAD HOLIDAY',
                    'dt' => '2020-12-01',
                    'guarantee_flag' => 0,
                    'states' => '"PJ","WP"',
                    'update_by' => 39868,
                    'action' => 'INSERT',
                    'created_at' => '2020-05-14 23:41:10',
                    'updated_at' => '2020-05-14 23:41:10',
                ),
                140 => 
                array (
                    'id' => 141,
                    'holiday_id' => 68,
                    'descr' => 'ITAAD HOLIDAY',
                    'dt' => '2020-12-01',
                    'guarantee_flag' => 0,
                    'states' => '"PJ","WP"',
                    'update_by' => 39868,
                    'action' => 'DESTROY',
                    'created_at' => '2020-05-14 23:41:58',
                    'updated_at' => '2020-05-14 23:41:58',
                ),
            ));
        
        
    }
}